spring.application.name= dental_pos

server.address=0.0.0.0
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://db-mysql-sgp1-97027-do-user-17023691-0.h.db.ondigitalocean.com:25060/dental_POS?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=false
spring.datasource.username=doadmin
spring.datasource.password=AVNS_0X9hkTpr_KO1ro9_I2K
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://localhost:3306/dental_POS?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=c0nf0rt@b!E
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.username=root
#spring.datasource.password=c0nf0rt@b!E
